### ISSUE TITLE
Error with using pondslider and mh_z19

### ISSUE THREAD

**Issue by HeikoGH** [UedaTakeyuki/pondslider#1]
Hello there,
thank you for providing the modules for the MH-Z19!
Using the mh_z19 python module works
```
pi@co2sensor:~/mh-z19 $ sudo python -m mh_z19 --all
{"co2": 1845, "temperature": 19, "TT": 59, "SS": 0, "UhUl": 1024}
pi@co2sensor:~/mh-z19 $
```
But I have problems using the pondslider module to publish the measurements.

I am running Raspian Buster (11) on a Raspberry Pi 3b.
When I try to call the pondslider module, I get this error
```
pi@co2sensor:~/mh-z19 $ sudo python -m pondslider --sensor_handlers mh_z19 
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/pondslider/__main__.py", line 68, in <module>
    pondslider.read(args.config)
AttributeError: module '__init__' has no attribute 'read'
pi@co2sensor:~/mh-z19 $ 
```
Do you have an idea what's going wrong? 
Thank you in advance!

**Comment by UedaTakeyuki** [comment]
Hi HeikoGH!

Thank you for your using pondslider and report me the issue.

I'm afraid that I have no idea.
Actually, module [__init__](https://github.com/UedaTakeyuki/pondslider/blob/master/pondslider/__init__.py) definitely　has function [read](https://github.com/UedaTakeyuki/pondslider/blob/master/pondslider/__init__.py#L21)

**Comment by FabianRueckert** [comment]
I have the same issue.

**Comment by UedaTakeyuki** [comment]
Sorry, but I have no idea.
How about moving this topic to [discussion](https://github.com/UedaTakeyuki/pondslider/discussions) and waiting for someone who has an idea.

**Comment by UedaTakeyuki** [comment]
I can reproduce this issue with bullseye, and fix it in the latest version.
